update 1006

diff --git a/applications/luci-app-xray/root/etc/init.d/xray b/applications/luci-app-xray/root/etc/init.d/xray
--- a/applications/luci-app-xray/root/etc/init.d/xray
+++ b/applications/luci-app-xray/root/etc/init.d/xray
@@ -1,136 +1,538 @@
 #!/bin/sh /etc/rc.common
+#
+# Copyright (C) 2020-2022 honwen <https://github.com/honwen>
+#
+# This is free software, licensed under the GNU General Public License v3.
+# See /LICENSE for more information.
+#
 
 START=90
 STOP=15
-USE_PROCD=1
+
 NAME=xray
+EXTRA_COMMANDS="rules healthcheck"
+CRON_FILE=/etc/crontabs/root
+WATCHDOG_ENDPOINT='accounts.gstatic.com'
 
-GENERATE_CONF="/usr/share/xray/gen_config.lua"
+DNSMASQDIR=$(sed -n 's+conf-dir=++p' /var/etc/dnsmasq.conf.* 2>/dev/null)
+[ "V$DNSMASQDIR" = "V" ] && DNSMASQDIR=/var/dnsmasq.d
 
-source /usr/share/xray/init.firewall
+uci_get_by_name() {
+	local ret=$(uci get $NAME.$1.$2 2>/dev/null)
+	echo ${ret:=$3}
+}
 
 uci_get_by_type() {
-    local ret=$(uci get ${NAME}.@$1[0].$2 2> /dev/null)
-    echo ${ret:=$3}
+	local ret=$(uci get $NAME.@$1[0].$2 2>/dev/null)
+	echo ${ret:=$3}
 }
 
-log_procd_set_param() {
-    local type="$1"
-    shift
-    logger -st xray[$$] -p4 "Using procd_set_param $type" "$@"
+uci_bool_by_name() {
+	case "$(uci_get_by_name $1 $2)" in
+	1 | on | true | yes | enabled) return 0 ;;
+	esac
+	return 1
 }
 
-start_xray() {
-    logger -st xray[$$] -p4 "Starting Xray from $1"
-    procd_open_instance
-    procd_set_param respawn 1 1 0
-    procd_set_param command $1
-    procd_append_param command run
-    procd_append_param command -confdir
-    procd_append_param command /var/etc/xray
+uci_bool_by_type() {
+	case "$(uci_get_by_type $1 $2)" in
+	1 | on | true | yes | enabled) return 0 ;;
+	esac
+	return 1
+}
 
-    local rlimit_nofile
-    if [ -s /usr/share/xray/rlimit_nofile ] ; then
-        rlimit_nofile="nofile=""$(cat /usr/share/xray/rlimit_nofile)"
-    fi
+random_id() {
+	/usr/bin/${NAME} uuid | sed 's+-.*++g'
+}
 
-    local rlimit_data
-    if [ -s /usr/share/xray/rlimit_data ] ; then
-        rlimit_data="data=""$(cat /usr/share/xray/rlimit_data)"
-    fi
+validate_server() {
+	[ "$(uci get $NAME.$1 2>/dev/null)" = "servers" ]
+}
 
-    # this param passing method is just so fucking weird
-    if [ -z "${rlimit_nofile}" ] ; then
-        if [ ! -z "${rlimit_data}" ]; then
-            log_procd_set_param limits "${rlimit_data}"
-            procd_set_param limits "${rlimit_data}"
-        fi
-    else
-        if [ -z "${rlimit_data}" ]; then
-            log_procd_set_param limits "${rlimit_nofile}"
-            procd_set_param limits "${rlimit_nofile}"
-        else
-            log_procd_set_param limits "${rlimit_data}" "${rlimit_nofile}"
-            procd_set_param limits "${rlimit_data}" "${rlimit_nofile}"
-        fi
-    fi
+has_valid_server() {
+	for server in $@; do
+		validate_server $server && return 0
+	done
+	return 1
+}
 
-    procd_set_param env XRAY_LOCATION_ASSET=/usr/share/xray
-    procd_set_param stdout 1
-    procd_set_param stderr 1
-    procd_set_param file /etc/config/xray
-    procd_set_param pidfile /var/run/xray.pid
-    procd_close_instance
+get_arg_udp() {
+	local server=$(uci_get_by_type transparent_proxy udp_relay_server)
+	[ "$server" = "same" ] || validate_server $server && echo "-u"
+}
+
+get_arg_out() {
+	case "$(uci_get_by_type access_control self_proxy 1)" in
+	1) echo "-o" ;;
+	2) echo "-O" ;;
+	esac
+}
+
+get_arg_tnd() {
+	uci_bool_by_type $1 no_delay && echo "--no-delay"
+}
+
+get_server_ips() {
+	echo $(uci_get_by_name $1 server)
+}
+
+get_lan_hosts() {
+	uci_bool_by_name $1 enable &&
+		echo "$(uci_get_by_name $1 type),$(uci_get_by_name $1 host)"
+}
+
+xray_cleandns() {
+	uci_bool_by_type general no_dns_injection && return 0
+
+	rm -f $DNSMASQDIR/ss.conf $DNSMASQDIR/ss-servers.conf 2>/dev/null
+}
+
+xray_injectdns() {
+	uci_bool_by_type general no_dns_injection && return 0
+
+	DNSconf=$DNSMASQDIR/xray-servers.conf
+	tmpDNSconf=$DNSMASQDIR/xray.conf
+	echo "all-servers" >$tmpDNSconf
+	config_load $NAME
+	for server in $(config_foreach get_server_ips servers | sort -u); do
+		cat <<-EOF >>$tmpDNSconf
+			ipset=/${server}/xray_spec_dst_bp
+			server=/${server}/#
+			server=/${server}/223.5.5.5
+			server=/${server}/119.29.29.29
+			server=/${server}/114.114.114.114
+			server=/${server}/80.80.80.80
+			server=/${server}/208.67.222.222#443
+			server=/${server}/208.67.220.220#5353
+		EOF
+	done
+
+	(grep -q 'no-resolv' /etc/dnsmasq.conf /etc/dnsmasq.d/* /var/dnsmasq.d/* /var/etc/dnsmasq.conf.* 2 >/dev/null) &&
+		sed "/\/#$/d" -i $tmpDNSconf
+	sort -u $tmpDNSconf | sed '/\/\//d; /\/127.0.0.1\//d' >$DNSconf
+	rm -f $tmpDNSconf
+
+	echo "server=/${WATCHDOG_ENDPOINT}/127.0.0.1#$(uci_get_by_type port_forward local_port 5300)" >>$DNSconf
+	[ -x /etc/init.d/dnsmasq-extra ] || {
+		echo "server=/${WATCHDOG_ENDPOINT}/208.67.222.222#443" >>$DNSconf
+		echo "server=/${WATCHDOG_ENDPOINT}/114.114.115.115" >>$DNSconf
+		echo "server=/${WATCHDOG_ENDPOINT}/80.80.80.80" >>$DNSconf
+	}
+
+	cat <<-EOF >>$DNSconf
+		server=/t.cn/223.5.5.5
+		server=/t.cn/119.29.29.29
+		server=/t.cn/114.114.114.114
+	EOF
+
+	/etc/init.d/dnsmasq restart >/dev/null 2>&1
+	# wait-for-dns, timeout 10s
+	for _ in $(seq 10); do if ping -4 -q -c 1 -s 0 -W 1 -w 1 t.cn >/dev/null 2>&1; then break; fi; done
+}
+
+start_rules() {
+	config_load $NAME
+	/usr/bin/${NAME}-rules \
+		-s "$(config_foreach get_server_ips servers | sort -u)" \
+		-l "$(uci_get_by_type transparent_proxy local_port 1234)" \
+		-B "$(uci_get_by_type access_control wan_bp_list)" \
+		-b "$(uci_get_by_type access_control wan_bp_ips)" \
+		-W "$(uci_get_by_type access_control wan_fw_list)" \
+		-w "$(uci_get_by_type access_control wan_fw_ips)" \
+		-I "$(uci_get_by_type access_control lan_ifaces)" \
+		-d "$(uci_get_by_type access_control lan_target)" \
+		-a "$(config_foreach get_lan_hosts lan_hosts)" \
+		-e "$(uci_get_by_type access_control ipt_ext)" \
+		$(get_arg_out) $(get_arg_udp)
+}
+
+rules() {
+	pgrep -f /usr/bin/${NAME} >/dev/null || return 0
+	start_rules || /usr/bin/${NAME}-rules -f
+}
+
+gen_config_inbound_redir() {
+	command -v xray >/dev/null 2>&1 || return 0
+	uci_bool_by_type 'transparent_proxy' 'enable' && cat <<-EOF
+		    {
+		      "protocol": "dokodemo-door",
+		      "port": $(uci_get_by_type transparent_proxy local_port),
+		      "address": "0.0.0.0",
+		      "settings": {
+		        "network": "tcp,udp",
+		        "followRedirect": true
+		      }
+		    },
+	EOF
+}
+
+gen_config_inbound_http() {
+	command -v xray >/dev/null 2>&1 || return 0
+	uci_bool_by_type 'http_proxy' 'enable' && cat <<-EOF
+		    {
+		      "protocol": "http",
+		      "port": $(uci_get_by_type http_proxy local_port),
+		      "address": "0.0.0.0"
+		    },
+	EOF
+}
+
+gen_config_inbound_socks5() {
+	command -v xray >/dev/null 2>&1 || return 0
+	uci_bool_by_type 'socks5_proxy' 'enable' && cat <<-EOF
+		    {
+		      "protocol": "socks",
+		      "port": $(uci_get_by_type socks5_proxy local_port),
+		      "address": "0.0.0.0",
+		      "settings": {
+		        "udp": true
+		      }
+		    },
+	EOF
+}
+
+gen_config_inbound_tunnel() {
+	command -v xray >/dev/null 2>&1 || return 0
+	uci_bool_by_type 'port_forward' 'enable' && cat <<-EOF
+		    {
+		      "protocol": "dokodemo-door",
+		      "port": $(uci_get_by_type port_forward local_port),
+		      "address": "0.0.0.0",
+		      "settings": {
+		        "address": "$(uci_get_by_type port_forward destination | sed 's+:.*++g')",
+		        "port": $(uci_get_by_type port_forward destination | sed 's+.*:++g'),
+		        "network": "tcp,udp"
+		      }
+		    },
+	EOF
+}
+
+gen_config_inbounds() {
+	cat <<-EOF | sed 's+,    +,\n    +g;s+},__$+}+g'
+		  "inbounds": [
+				$(gen_config_inbound_redir)$(gen_config_inbound_http)$(gen_config_inbound_socks5)$(gen_config_inbound_tunnel)__
+		  ],
+	EOF
+}
+
+gen_stream_setting_key() {
+	network=$1
+	security=$2
+	echo $network >/var/run/network
+	echo $security >/var/run/security
+	if [ "V${network}" = "Vquic" ]; then
+		echo -e "\"quicSettings\": {},\n        \"${security}Settings\""
+	else
+		echo "\"${security}Settings\""
+	fi
+}
+
+gen_xtls_flow() {
+	local security=$(uci_get_by_name $1 security | sed 's+-.*++g')
+	local flow=$(uci_get_by_name $1 security | sed 's+.*-++g')
+	[ "V${flow}" == 'Vxtls' ] && flow='splice'
+	if [ "V${security}" == 'Vxtls' ]; then
+		echo -e "\n                \"flow\": \"xtls-rprx-${flow}\","
+	fi
+}
+
+gen_server_vless_config() {
+	local network='tcp'
+	local security=$(uci_get_by_name $1 security 'tls' | sed 's+-.*++g')
+	[ "V${security}" = "Vquic" ] && {
+		sysctl -w net.core.rmem_max=250000 >/dev/null
+		network='quic'
+		security='tls'
+	}
+	validate_server $1 && {
+		serverName=$(uci_get_by_name $1 server_name)
+		[ "V$serverName" = "V" ] && serverName=$(uci_get_by_name $1 server)
+		cat <<-EOF
+			    {
+			      "tag": "dummy-$(random_id)",
+			      "protocol": "$(uci_get_by_name $1 protocol)",
+			      "settings": {
+			        "vnext": [
+			          {
+			            "address": "$(uci_get_by_name $1 server)",
+			            "port": $(uci_get_by_name $1 server_port),
+			            "users": [
+			              {
+			                "id": "$(uci_get_by_name $1 id)",$(gen_xtls_flow $1)
+			                "encryption": "none",
+			                "level": 0
+			              }
+			            ]
+			          }
+			        ]
+			      },
+			      "streamSettings": {
+			        "network": "${network}",
+			        "security": "${security}",
+			        $(gen_stream_setting_key ${network} ${security}): {
+			          "serverName": "${serverName}"
+			        }
+			      }
+			    },
+		EOF
+	}
+}
+
+gen_server_trojan_config() {
+	local network='tcp'
+	local security=$(uci_get_by_name $1 security 'tls' | sed 's+-.*++g')
+	[ "V${security}" = "Vquic" ] && {
+		sysctl -w net.core.rmem_max=250000 >/dev/null
+		network='quic'
+		security='tls'
+	}
+	validate_server $1 && {
+		serverName=$(uci_get_by_name $1 server_name)
+		[ "V$serverName" = "V" ] && serverName=$(uci_get_by_name $1 server)
+		cat <<-EOF
+			    {
+			      "tag": "dummy-$(random_id)",
+			      "protocol": "$(uci_get_by_name $1 protocol)",
+			      "settings": {
+			        "servers": [
+			          {
+			            "address": "$(uci_get_by_name $1 server)",
+			            "port": $(uci_get_by_name $1 server_port),
+			            "password": "$(uci_get_by_name $1 id)",
+			            "level": 0
+			          }
+			        ]
+			      },
+			      "streamSettings": {
+			        "network": "${network}",
+			        "security": "${security}",
+			        $(gen_stream_setting_key ${network} ${security}): {
+			          "serverName": "${serverName}"
+			        }
+			      }
+			    },
+		EOF
+	}
+}
+
+gen_server_shadowsocks_config() {
+	validate_server $1 && {
+		cat <<-EOF
+			    {
+			      "tag": "dummy-$(random_id)",
+			      "protocol": "$(uci_get_by_name $1 protocol)",
+			      "settings": {$(get_plugin_config $1)
+			        "servers": [
+			          {
+			            "address": "$(uci_get_by_name $1 server)",
+			            "port": $(uci_get_by_name $1 server_port),
+			            "password": "$(uci_get_by_name $1 id)",
+			            "method": "$(uci_get_by_name $1 security)"
+			          }
+			        ]
+			      }
+			    },
+		EOF
+	}
+}
+
+get_plugin_config() {
+	local plugin=$(which $(uci_get_by_name $1 plugin))
+	local plugin_opts=$(uci_get_by_name $1 plugin_opts)
+	if [ -n "$plugin" ]; then
+		echo $plugin >>/var/run/xray-plugin
+		echo -e "\n        \"plugin\": \"$plugin\","
+		if [ -n "$plugin_opts" ]; then
+			echo "        \"pluginOpts\": \"$plugin_opts\","
+		fi
+	fi
+}
+
+gen_server_config() {
+	local protocol=$(uci_get_by_name $1 protocol)
+	if [ "V${protocol}" = "Vvless" ]; then
+		gen_server_vless_config $1
+	elif [ "V${protocol}" = "Vtrojan" ]; then
+		gen_server_trojan_config $1
+	elif [ "V${protocol}" = "Vshadowsocks" ]; then
+		gen_server_shadowsocks_config $1
+	else
+		echo "# Err: protocol[$protocol] not supported!"
+		exit 1
+	fi
+}
+
+gen_config_outbounds() {
+	cat <<-EOF | sed 's+,    +,\n    +g;s+},__$+}+g'
+		  "outbounds": [
+					$(for server in $(uci_get_by_type general server); do gen_server_config $server; done)__
+		  ],
+	EOF
 }
 
 gen_config_file() {
-    rm -f /var/etc/xray/*
-    if [ -s /usr/share/xray/infinite_retry ] ; then
-        while [ ! -s /var/etc/xray/config.json ] ; do
-            logger -st xray[$$] -p4 "(Re)generating Xray configuration files..."
-            /usr/bin/lua ${GENERATE_CONF} > /var/etc/xray/config.json
-        done
-    else
-        logger -st xray[$$] -p4 "Generating Xray configuration files..."
-        /usr/bin/lua ${GENERATE_CONF} > /var/etc/xray/config.json
-    fi
-    local custom_config=$(uci_get_by_type general custom_config)
-    [ ! "${#custom_config}" == "0" ] && echo ${custom_config} > /var/etc/xray/config_custom.json
+	local config_file=/var/etc/$NAME.json
+	local balancer_name="balancer-$(random_id)"
+	cat <<-EOF >$config_file
+		{
+			$(gen_config_inbounds)
+			$(gen_config_outbounds)
+		  "routing": {
+		    "domainStrategy": "AsIs",
+		    "domainMatcher": "mph",
+		    "rules": [{
+		      "type": "field",
+		      "network": "tcp,udp",
+		      "balancerTag": "${balancer_name}"
+		    }],
+		    "balancers": [{
+		      "tag": "${balancer_name}",
+		      "selector": ["dummy"],
+		      "strategy": {
+		      "type": "$(uci_get_by_type general strategy leastPing)"
+		      }
+		    }]
+		  },
+		  "observatory": {
+		    "subjectSelector": [ "outbound" ],
+		    "probeURL": "http://${WATCHDOG_ENDPOINT}/generate_204"
+		  },
+		  "log": {
+		    "loglevel": "warning"
+		  }
+		}
+	EOF
+	echo $config_file
 }
 
-setup_dnsmasq() {
-    local dns_port=$(uci_get_by_type general dns_port)
-    local dns_count=$(uci_get_by_type general dns_count 0)
-
-    echo "# Generated dnsmasq configurations by luci-app-xray" > /tmp/dnsmasq.d/xray.conf
-    echo "strict-order" >> /tmp/dnsmasq.d/xray.conf
-    echo "server=/#/127.0.0.1#${dns_port}" >> /tmp/dnsmasq.d/xray.conf
-    local cur_port
-    for cur_port in $(seq ${dns_port} $(expr ${dns_port} + ${dns_count})); do
-        echo "server=127.0.0.1#${cur_port}" >> /tmp/dnsmasq.d/xray.conf
-    done
-
-    logger -st xray[$$] -p4 $(cat /tmp/dnsmasq.d/xray.conf)
-    /etc/init.d/dnsmasq restart > /dev/null 2>&1
+xray_daemon() {
+	command -v xray >/dev/null 2>&1 || return 0
+	(/usr/bin/${NAME} run -c $(gen_config_file) >/var/log/xray.log 2>&1) &
+	for _ in $(seq 10); do if pgrep -f /usr/bin/${NAME} >/dev/null; then break; else sleep 1; fi; done
+	pgrep -f /usr/bin/${NAME} >/dev/null
 }
 
-flush_dnsmasq() {
-    rm /tmp/dnsmasq.d/xray.conf
-    /etc/init.d/dnsmasq restart > /dev/null 2>&1
+start() {
+	pgrep -f /usr/bin/${NAME} >/dev/null && return 0
+	uci_bool_by_type 'transparent_proxy' 'enable' ||
+		uci_bool_by_type 'port_forward' 'enable' ||
+		uci_bool_by_type 'http_proxy' 'enable' ||
+		uci_bool_by_type 'socks5_proxy' 'enable' ||
+		return 0
+
+	mkdir -p /var/run /var/etc $DNSMASQDIR
+	has_valid_server $(uci_get_by_type general server) && {
+		xray_injectdns
+		xray_daemon
+	}
+	uci_bool_by_type 'transparent_proxy' 'enable' && {
+		rules
+		add_cron
+	}
 }
 
-create_when_enable() {
-    [ "$(uci_get_by_type general transparent_proxy_enable)" == "1" ] || return 0
-    logger -st xray[$$] -p4 "Setting dnsmasq and firewall for transparent proxy..."
-    setup_dnsmasq
-    setup_firewall
+boot() {
+	echo 'exit 0' >/var/etc/$NAME.include
+	local delay=$(uci_get_by_type general startup_delay 0)
+	(sleep $delay && start >/dev/null 2>&1) &
+	return 0
 }
 
-flush_when_disable() {
-    logger -st xray[$$] -p4 "Resetting dnsmasq and firewall configurations..."
-    flush_dnsmasq
-    flush_firewall
+kill_all() {
+	kill -9 $(pgrep -f $@) >/dev/null 2>&1
 }
 
-start_service() {
-    config_load $NAME
-    mkdir -p /var/run /var/etc/xray
-    local xray_bin=$(uci_get_by_type general xray_bin)
-    command -v ${xray_bin} > /dev/null 2>&1 || return 1
-    gen_config_file
-    start_xray ${xray_bin}
-    create_when_enable || flush_when_disable
+stop() {
+	/usr/bin/${NAME}-rules -f
+	kill_all /usr/bin/${NAME}
+	if [ -f /var/run/xray-plugin ]; then
+		kill_all $(sort -u /var/run/xray-plugin)
+		rm -f /var/run/xray-plugin
+	fi
+	xray_cleandns
+	del_cron
 }
 
-stop_service() {
-    flush_when_disable
+add_cron() {
+	[ -f $CRON_FILE ] || return 0
+	uci_bool_by_type transparent_proxy no_healthcheck && return 0
+
+	sed -i '/xray_healthcheck/d' $CRON_FILE
+	echo '0   */3   * * *  rm -f /var/log/xray_healthcheck.log 2>&1' >>$CRON_FILE
+	echo '*    *    * * * /etc/init.d/xray healthcheck >> /var/log/xray_healthcheck.log 2>&1' >>$CRON_FILE
+	/etc/init.d/cron restart
 }
 
-reload_service() {
-    stop
-    start
+del_cron() {
+	[ -f $CRON_FILE ] || return 0
+	uci_bool_by_type transparent_proxy no_healthcheck && return 0
+
+	sed -i '/xray_healthcheck/d' $CRON_FILE
+	/etc/init.d/cron restart
 }
 
-service_triggers() {
-    procd_add_reload_trigger "xray"
+healthcheck() {
+	command -v xray >/dev/null 2>&1 || return 1
+	has_valid_server $(uci_get_by_type general server) && uci_bool_by_type 'transparent_proxy' 'enable' || return 1
+	uci_bool_by_type transparent_proxy no_healthcheck && return 0
+
+	LOGTIME=$(date "+%Y-%m-%d %H:%M:%S")
+	pgrep -f "/var/etc/$NAME.json" >/dev/null 2>&1 || {
+		echo "[${LOGTIME}] Problem decteted, restarting ${NAME}..."
+		stop >/dev/null 2>&1
+		start >/dev/null 2>&1
+		return 0
+	}
+
+	cat_connect() {
+		target="$1"
+		retry=${2:-1}
+		timeout=5
+		[ $retry -lt 1 ] && return 1
+		ret_code=$(curl -s --connect-timeout $timeout "$target" -w %{http_code} -o /dev/null | tail -n1)
+		# echo -n "[ $retry $ret_code ] "
+		[ "x$ret_code" = "x200" -o "x$ret_code" = "x204" ] && return 0 || sleep 1 && cat_connect $target $((retry - 1))
+	}
+
+	TRPORT=$(uci_get_by_type transparent_proxy local_port 1234)
+	GOOGLE=$(ping -4 -q -c 1 -s 0 -W 1 -w 1 ${WATCHDOG_ENDPOINT} 2>/dev/null | sed '1{s/[^(]*(//;s/).*//;q}')
+	DNSPOD=119.29.29.98 #DNSPOD HTTPDNS (Inside GFW)
+
+	if [ "Z$GOOGLE" = "Z" ]; then
+		iptables -t nat -I OUTPUT -p tcp -d $DNSPOD -j RETURN
+		cat_connect "http://${DNSPOD}/d"
+		if [ "Z$?" = "Z0" ]; then
+			echo "[${LOGTIME}] Problem-DNS decteted, restarting ${NAME}..."
+			[ -x /etc/init.d/dnsmasq-extra ] && /etc/init.d/dnsmasq-extra restart || /etc/init.d/dnsmasq restart
+			stop >/dev/null 2>&1
+			start >/dev/null 2>&1
+		else
+			echo '['$LOGTIME'] Network Problem. Do nothing.'
+		fi
+		iptables -t nat -D OUTPUT -p tcp -d $DNSPOD -j RETURN
+		return 0
+	fi
+
+	iptables -t nat -I OUTPUT -p tcp -d $GOOGLE -j REDIRECT --to-port $TRPORT
+	iptables -t nat -I OUTPUT -p tcp -d $DNSPOD -j RETURN
+	cat_connect "http://${GOOGLE}/generate_204" 3
+	if [ "Z$?" = "Z0" ]; then
+		echo "[${LOGTIME}] ${NAME} No Problem."
+	else
+		# cat_connect "http://wifi.vivo.com.cn/generate_204"
+		# cat_connect "http://www.qualcomm.cn/generate_204"
+		cat_connect "http://${DNSPOD}/d"
+		if [ "Z$?" = "Z0" ]; then
+			echo "[${LOGTIME}] Problem decteted, restarting ${NAME}..."
+			[ -x /etc/init.d/haproxy-tcp ] && /etc/init.d/haproxy-tcp restart
+			stop >/dev/null 2>&1
+			start >/dev/null 2>&1
+		else
+			echo '['$LOGTIME'] Network Problem. Do nothing.'
+		fi
+	fi
+
+	iptables -t nat -D OUTPUT -p tcp -d $GOOGLE -j REDIRECT --to-port $TRPORT
+	iptables -t nat -D OUTPUT -p tcp -d $DNSPOD -j RETURN
+	return 0
 }
